let machidx=[];    //array for machine input
let useridx=[];    //array for user input
let btns=["blue","green","yellow","red"];
let bt=document.querySelectorAll(".bt");

let game=false;
let level=0;
let h4=document.querySelector("h4");

let bdy=document.querySelector("body");
bdy.addEventListener("keypress",function start(){
    // btnflash();
    mecrandom();
    
});

//function for generating random number as a index and flash random button on that index.
function mecrandom(){
    useridx=[];
    game=true;
    level++;
    h4.innerText=`Level ${level}`;
    let randomidx=Math.floor(Math.random()*4);
    let randcolor=btns[randomidx];
    let randbtn=document.querySelector(`.${randcolor}`);
    // console.log(randomidx);
    // console.log(randcolor);
    // console.log(randbtn);
    btnflash(randbtn);
    machidx.push(randcolor); //push the button value generated by machine in our array
    //console.log(machidx);
};

//function for flashing the button
function btnflash(btn){
    btn.classList.add("flash");
    setTimeout(() => {
        btn.classList.remove("flash");
    }, 200);
};

//function for press button by user
function btnpress(){
    let btn=this;
    btnflash(btn);
    btncolor=btn.getAttribute("id");
    // console.log(btncolor);
    useridx.push(btncolor);
    console.log(useridx);
    match(useridx.length-1);
};
for(btn of bt){
    btn.addEventListener("click",btnpress);
};

//function to match the machie index and user index
function match(idx){
    // let idx=level-1;
    if(machidx[idx]===useridx[idx]){
        if(machidx.length==useridx.length){
        setTimeout(mecrandom,1000);
        }
    }
    else{
        h4.innerHTML=`Game is over! your score is ${level}. Press any key to start the game. `;
        reset();
    }
};

//function to reset the game when user enter wrong input
function reset(){
    bdy.classList.add("bdy");
    setTimeout(()=>{
        bdy.classList.remove("bdy");
    },200)
    game=false;
    machidx=[];
    useridx=[];
    level=0;
};